UPSY-group/UPSY-models

config-files/config_test_01.cfg
src/UFEMISM_main_model.f90
src/basal_conditions/basal_hydrology.f90
src/basal_conditions/bed_roughness.f90
src/basal_conditions/sliding_laws.f90
src/ice/ice_model_main.f90
src/ice/ice_model_memory.f90
src/ice/ice_model_scalars.f90
src/ice/ice_model_utilities.f90
src/ice/ice_velocity_SIA.f90
src/ice/ice_velocity_SSA.f90
src/reference_states/reference_geometries.f90

All distributed arrays are now indexed mesh%vi1:mesh%vi2 (or ti1,ti2 in the case of b-grid data).

Feature fix indexing

---

src/ice/ice_thickness.f90

Merge Jorjo's time step condition into mesh update branch

---

automated_testing/component_tests/analyse_component_tests.m
automated_testing/component_tests/analyse_discretisation_tests.m
automated_testing/component_tests/analyse_mapping_derivative_tests.m
automated_testing/component_tests/analyse_remapping_tests.asv
automated_testing/component_tests/analyse_remapping_tests.m
automated_testing/component_tests/analyse_remapping_tests_grid_to_mesh.m
automated_testing/component_tests/analyse_remapping_tests_mesh_to_grid.m
src/Makefile
src/validation/component_tests.f90
src/validation/component_tests_create_test_meshes.f90
src/validation/component_tests_discretisation.f90
src/validation/component_tests_discretisation_mapping_derivatives.f90
src/validation/component_tests_remapping.f90
src/validation/component_tests_remapping_basic.f90
src/validation/component_tests_remapping_grid_to_mesh.f90
src/validation/component_tests_remapping_mesh_to_grid.f90
tools/matlab/bluewhiteredmap.m

Add component tests for grid-to-mesh and mesh-to-grid remapping, plus Matlab analysis script.

Remapping component tests

---

.github/workflows/UFE_test_suite.yml
automated_testing/component_tests/analyse_component_tests.m
automated_testing/component_tests/analyse_discretisation_tests.m
automated_testing/component_tests/analyse_mapping_derivative_tests.m
automated_testing/component_tests/analyse_remapping_tests.asv
automated_testing/component_tests/analyse_remapping_tests.m
automated_testing/component_tests/analyse_remapping_tests_grid_to_mesh.m
automated_testing/component_tests/analyse_remapping_tests_mesh_to_grid.m
src/Makefile
src/validation/component_tests.f90
src/validation/component_tests_create_test_meshes.f90
src/validation/component_tests_discretisation.f90
src/validation/component_tests_discretisation_mapping_derivatives.f90
src/validation/component_tests_remapping.f90
src/validation/component_tests_remapping_basic.f90
src/validation/component_tests_remapping_grid_to_mesh.f90
src/validation/component_tests_remapping_mesh_to_grid.f90
tools/matlab/bluewhiteredmap.m

merge main into feature branch

---

src/basic/model_configuration.f90
src/netcdf/netcdf_basic.f90

Add git hash string to netcdf output

---

src/Makefile
src/basal_conditions/basal_hydrology.f90
src/basal_conditions/bed_roughness.f90
src/basic/math_utilities/math_utilities.f90
src/basic/precisions.f90
src/basic/reallocate_mod.f90
src/ice/ice_model_main.f90
src/ice/ice_model_utilities.f90
src/main/UFEMISM_main_model.f90
src/mesh/mesh_utilities.f90
src/tracer_tracking/tracer_tracking_main.f90
src/tracer_tracking/tracer_tracking_particles.f90
src/types/region_types.f90
src/types/tracer_tracking_model_types.f90
src/validation/unit_tests/unit_tests.f90
src/validation/unit_tests/ut_tracer_tracking.f90
tools/matlab/find_containing_vertex.m

Added some basic functionality for the new tracer tracking module:
- mapping of ice velocity components to the tracer particles
- mapping of tracer data to the mesh
- add/move/remove particles

Tracer tracking basics

---

.github/workflows/UFE_test_suite_finalise_scoreboard.yml
.github/workflows/UFE_test_suite_run_and_analyse_integrated_tests.yml
.github/workflows/zz_integrated_tests_idealised_Halfar_dome_Halfar_static_10km.yml
.github/workflows/zz_integrated_tests_idealised_Halfar_dome_Halfar_static_20km.yml
.github/workflows/zz_integrated_tests_idealised_Halfar_dome_Halfar_static_40km.yml
.github/workflows/zz_integrated_tests_idealised_Halfar_dome_Halfar_static_5km.yml
automated_testing/integrated_tests/idealised/Halfar_dome/Halfar_static_10km/analyse_integrated_test.m
automated_testing/integrated_tests/idealised/Halfar_dome/Halfar_static_10km/config.cfg
automated_testing/integrated_tests/idealised/Halfar_dome/Halfar_static_20km/analyse_integrated_test.m
automated_testing/integrated_tests/idealised/Halfar_dome/Halfar_static_20km/config.cfg
automated_testing/integrated_tests/idealised/Halfar_dome/Halfar_static_40km/analyse_integrated_test.m
automated_testing/integrated_tests/idealised/Halfar_dome/Halfar_static_40km/config.cfg
automated_testing/integrated_tests/idealised/Halfar_dome/Halfar_static_5km/analyse_integrated_test.m
automated_testing/integrated_tests/idealised/Halfar_dome/Halfar_static_5km/config.cfg
src/surface_mass_balance/SMB_idealised.f90

Added the analytical solution for the SMB to create the static Halfar dome. Added 4 versions of this experiment as integrated tests.

Static halfar dome

---

src/basal_conditions/basal_hydrology.f90
src/basal_conditions/basal_inversion_H_dHdt_flowline.f90
src/basal_conditions/sliding_laws.f90
src/basic/grid_basic.f90
src/basic/grid_lonlat_basic.f90
src/basic/mpi_distributed_memory.f90
src/basic/petsc_basic.f90
src/ice/ice_model_main.f90
src/ice/ice_model_scalars.f90
src/ice/ice_model_utilities.f90
src/ice/ice_thickness.f90
src/ice/ice_velocity_BPA.f90
src/ice/ice_velocity_DIVA.f90
src/ice/ice_velocity_SSA.f90
src/ice/ice_velocity_hybrid_DIVA_BPA.f90
src/ice/ice_velocity_main.f90
src/main/UFEMISM_main_model.f90
src/mesh/creation/reduce_ice_geometry.f90
src/mesh/discretisation/mesh_disc_apply_operators.f90
src/mesh/mesh_utilities.f90
src/mesh/remapping/apply_maps.f90
src/netcdf/netcdf_debug.f90
src/netcdf/netcdf_input.f90
src/netcdf/netcdf_output.f90
src/thermodynamics/thermodynamics_utilities.f90
src/validation/component_tests/ct_remapping_mesh_to_mesh.f90
src/validation/unit_tests/ut_mpi.f90
src/validation/unit_tests/ut_tracer_tracking.f90

Create generic interfaces for the gather_to_all, gather_to_master, and distribute_from_master routines.

Refactor mpi distributed memory

---

src/basic/model_configuration.f90
src/main/main_regional_output.f90
src/netcdf/netcdf_output.f90
tools/matlab/read_matrix_operators_from_file.m

Write the operator matrices to the mesh output file (optionally), useful for debugging/prototyping in Matlab

Write operator matrices to output

---

src/laddie/laddie_tracers.f90
src/laddie/laddie_utilities.f90
src/laddie/laddie_velocity.f90

Modified some partial variables to total variables to make Laddie work on multiple cores.

fix bunch of _tot variables

---

src/basal_conditions/basal_hydrology.f90
src/basal_mass_balance/BMB_prescribed.f90
src/thermodynamics/thermodynamics_main.f90

Restart from last fix

---

automated_testing/integrated_tests/idealised/SSA_icestream/analyse_integrated_test.m
src/io/transects/transects_main.f90
src/types/transect_types.f90

To compare with ApRES measurements

Add all velocities and the principal strain rates to transect output

---

src/Makefile
src/io/netcdf_basic/netcdf_field_name_options.f90
src/io/netcdf_output/netcdf_setup_grid_mesh_in_file.f90
src/mesh/edges/mesh_edges.f90
src/mesh/mesh_integrate_over_domain.f90
src/mesh/mesh_utilities.f90
src/types/mesh_types.f90
tools/matlab/read_mesh_from_file.m

Average over triangles

---

.github/workflows/UFE_test_suite.yml
.github/workflows/UFE_test_suite_compile_and_cache_UFEMISM_dev_Linux.yml
.github/workflows/UFE_test_suite_compile_and_cache_UFEMISM_dev_MacOS.yml
.github/workflows/UFE_test_suite_compile_and_cache_UFEMISM_perf_Linux.yml
.github/workflows/UFE_test_suite_compile_and_cache_UFEMISM_perf_MacOS.yml
CMakeLists.txt

Added two automated tests for compiling UFEMISM (both the development and performance builds) on Linux. Works like a charm.

Test compiling on linux

---

.gitmodules
src/laddie/laddie_dummy_domain.f90
src/laddie/laddie_integration.f90
src/laddie/laddie_main.f90
src/laddie/laddie_operators.f90
src/laddie/laddie_output.f90
src/laddie/laddie_physics.f90
src/laddie/laddie_thickness.f90
src/laddie/laddie_tracers.f90
src/laddie/laddie_utilities.f90
src/laddie/laddie_velocity.f90

Laddie returns

---

src/UPSY/basic/math_utilities/switch_array_elements.f90
src/UPSY/mesh/Delaunay/switch_vertices_triangles.f90
src/UPSY/mesh/mesh_parallel_creation.f90

In preparation for adding delete_vertex

Refactor switch vertices

---

.github/workflows/LADDIE_test_suite.yml
.github/workflows/LADDIE_test_suite_compile_and_cache_dev_Linux.yml

Add working linux compilation workflow

Laddie linux

---

src/UPSY/mesh/Delaunay/basic_mesh_data_operations.f90
src/UPSY/mesh/Delaunay/delete_vertices.f90
src/UPSY/mesh/Delaunay/delete_vertices_local_geometry.f90
src/UPSY/validation/unit_tests/ut_mesh_refinement.f90

Fix delete_vertex

---

src/UPSY/mesh/Voronoi_mesh/mesh_Voronoi.f90
src/UPSY/mesh/edges/mesh_edges.f90
src/UPSY/mesh/mesh_focussing.f90
src/UPSY/mesh/mesh_parallelisation.f90
src/UPSY/mesh/mesh_zeta.f90
src/UPSY/types/polyline_types.f90
src/UPSY/validation/unit_tests/ut_mesh_delete_vertices.f90
src/UPSY/validation/unit_tests/ut_mesh_refinement.f90

Delete all vertices whose Voronoi cell intersects with a given line. Why? Don't ask!

Add delete vertices along line

---

CMakeLists.txt
src/LADDIE/laddie_thickness.f90
src/LADDIE/laddie_tracers.f90
src/LADDIE/laddie_utilities.f90
src/LADDIE/laddie_velocity.f90
src/LADDIE/main/LADDIE_program.f90
src/UFEMISM/main/UFEMISM_program.f90
src/UPSY/basic/control_resources_and_error_messaging.f90
tools/python/colormaps.py
tools/python/main_figure.py
tools/python/main_mesh.py

Seem to have fixed the parallellisation error by adding a bunch of call sync statements. The vertical stripes seem to have disappeared (only local tests for now) and runs on slightly different number of cores seem to show the same, stable result:
Before this fix, a run on 8 cores showed:
And on 9 cores:
Note that the major instability probably arises on the border between cores 6 and 7, as this local laptop has 6 fast cores and a bunch of slower ones. Hence any sync-issues are likely strongest at this border.
After the fix, 8 cores:
And 9 cores:

Laddie stability

---

src/UFEMISM/ice_dynamics/ice_dynamics_main.f90
src/UFEMISM/main/UFEMISM_main_model.f90

Add the case for remap with a 'prescribed' sea level in the subroutine remap_basic_ice_geometry

add option for remap with prescribed sea level

---

src/UPSY/mesh/graph/create_graphs_from_masked_mesh.f90
src/UPSY/mesh/graph/graph_parallelisation.f90
src/UPSY/mesh/mesh_parallelisation.f90
src/UPSY/types/graph_types.f90
src/UPSY/validation/unit_tests/ut_mesh_graphs.f90

Add graph parallelisation

---

src/UFEMISM/ice_dynamics/conservation_of_momentum/SSA_DIVA/DIVA_infinite_slab.f90
src/UFEMISM/ice_dynamics/conservation_of_momentum/SSA_DIVA/DIVA_main.f90
src/UFEMISM/ice_dynamics/conservation_of_momentum/hybrid_DIVA_BPA/hybrid_DIVA_BPA_main.f90
src/UPSY/basic/model_configuration.f90

Can you guess what's coming next?

Specify infinite slab BC
